language: objective-c
osx_image: xcode9

before_install:
  - gem install cocoapods

script:
    - xcodebuild clean test -workspace FireBaseLoginRegister.xcworkspace -scheme FireBaseLoginRegisterTests -destination "platform=iOS Simulator,name=iPhone 7,OS=10.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
