language: objective-c
osx_image: xcode9
cache: cocoapods
xcode_workspace: FireBaseLoginRegister.xcworkspace # path to your xcodeproj folder
xcode_scheme: FireBaseLoginRegisterTests

before_install:
  - gem install cocoapods

install:
  - pod install